export const FOOTER = {
  categories: [
    "Popular",
    "Arts & culture",
    "Outdoors",
    "Mountains",
    "Beach",
    "Unique stays",
    "Categories",
    "Things to do",
    "Travel tips & inspiration",
    "Airbnb-friendly apartments",
  ],
  locations: [
    { title: "Canmore", subtitle: "Condo rentals" },
    { title: "Benalmádena", subtitle: "Beach house rentals" },
    { title: "Marbella", subtitle: "House rentals" },
    { title: "Mijas", subtitle: " Apartment rentals" },
    { title: "Prescott", subtitle: " Cabin rentals" },
    { title: "Scottsdale", subtitle: " Mansion rentals" },
    { title: "Tucson", subtitle: " Apartment rentals" },
    { title: "Jasper", subtitle: " Cabin rentals" },
    { title: "Mountain View", subtitle: " Cabin rentals" },
    { title: "Devonport", subtitle: " Cottage rentals" },
    { title: "Mallacoota", subtitle: " Beach house rentals" },
    { title: "Ibiza", subtitle: " Vacation rentals" },
    { title: "Anaheim", subtitle: " Apartment rentals" },
    { title: "Monterey", subtitle: " Condo rentals" },
    { title: "Paso Robles", subtitle: " Cottage rentals" },
    { title: "Santa Barbara", subtitle: " Apartment rentals" },
    { title: "Sonoma", subtitle: "Cottage rentals" },
  ],
  links: {
    support: [
      "Help Center",
      "AirCover",
      "Anti-discrimination",
      "Disability support",
      "Cancellation options",
      "Report neighborhood concern",
    ],
    hosting: [
      "Airbnb your home",
      "AirCover for Hosts",
      "Hosting resources",
      "Community forum",
      "Hosting responsibly",
      "Airbnb-friendly apartments",
      "Join a free Hosting class",
      "Find a co-host",
    ],
    internal: [
      "Newsroom",
      "New features",
      "Careers",
      "Investors",
      "Gift cards",
      "Airbnb.org emergency stays",
    ],
  },
};
